#!/bin/bash

go get github.com/mitchellh/gox

rm -rf output
version=$(git describe --abbrev=0 --tags)
gitrev=$(git rev-parse --short HEAD)
ldflags="-X \"main.gitrev=$gitrev\" -X \"main.version=$version\" -s -w -extldflags -static"
CGO_ENABLED=0 gox -os linux -arch amd64 -output "output/kafkatools_{{.OS}}_{{.Arch}}/{{.Dir}}" -ldflags="$ldflags" ./cmd/...

cd output

for file in * ; do
    if [[ -d "$file" ]]; then
        tar -czf "$file.tar.gz" "$file"
        # rm -r "$file"
    fi
done

echo "Built the following artifacts:"
ls -lh *.tar.gz
